In [14]:
import numpy as np

# Array operations: Size, Shape, Axes


In [ ]:


a = np.array([0,1,3,4,5,6])
b = np.array([2,3,4,5,6,7])

print(a.shape)

print (b.shape)

In [18]:
a + 3




array([0. , 0.5, 1.5, 2. , 2.5, 3. ])

In [19]:
a*2



array([ 0,  2,  6,  8, 10, 12])

In [20]:

a/2

array([0. , 0.5, 1.5, 2. , 2.5, 3. ])

In [21]:
a+b

array([ 2,  4,  7,  9, 11, 13])

In [22]:
a-b

array([-2, -2, -1, -1, -1, -1])

In [24]:

i=np.ones((3, 3), dtype=np.int16)
print(i)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
o = np.arange(1, 10, 1)
print(o)


[1 2 3 4 5 6 7 8 9]


In [26]:
o.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
o = np.arange(1, 7, 1)
print(o)

[1 2 3 4 5 6]


In [58]:
o=o.reshape(3,2)
print(o)

[[1 2]
 [3 4]
 [5 6]]


In [59]:
o=o.swapaxes(0,1)
print(o)

[[1 3 5]
 [2 4 6]]


In [61]:
o.shape

(2, 3)

In [62]:
o.ndim

2

In [64]:
o.size

6

# Slicing and Dicing

In [73]:
print(o)

[[1 3 5]
 [2 4 6]]


In [67]:
print(o[1:])


[[2 4 6]]


In [71]:
print(o[0::2])

[[1 3 5]]


In [74]:
print(o[:, 2:3])




[[5]
 [6]]


# Multidimensional arrays

In [83]:
a_3d = np.array([[[ 1,  2,  3],
                  [ 4,  5,  6],
                  [ 7,  8,  9]],

                 [[ 10, 11,12],
                  [ 13, 14,15],
                  [ 16, 17,18]],

                 [[ 19, 20,21],
                  [ 22, 23,24],
                  [ 25, 26, 27]]])



In [87]:
a_3d[2,1,:]

array([22, 23, 24])

In [89]:
a_3d[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])